/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as SeniorRouteImport } from './routes/senior'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as EnergieRouteImport } from './routes/energie'
import { Route as EclairageRouteImport } from './routes/eclairage'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AccesRouteImport } from './routes/acces'
import { Route as IndexRouteImport } from './routes/index'

const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorRoute = SeniorRouteImport.update({
  id: '/senior',
  path: '/senior',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergieRoute = EnergieRouteImport.update({
  id: '/energie',
  path: '/energie',
  getParentRoute: () => rootRouteImport,
} as any)
const EclairageRoute = EclairageRouteImport.update({
  id: '/eclairage',
  path: '/eclairage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesRoute = AccesRouteImport.update({
  id: '/acces',
  path: '/acces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/connexion': typeof ConnexionRoute
  '/eclairage': typeof EclairageRoute
  '/energie': typeof EnergieRoute
  '/securite': typeof SecuriteRoute
  '/senior': typeof SeniorRoute
  '/utilisateurs': typeof UtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/connexion': typeof ConnexionRoute
  '/eclairage': typeof EclairageRoute
  '/energie': typeof EnergieRoute
  '/securite': typeof SecuriteRoute
  '/senior': typeof SeniorRoute
  '/utilisateurs': typeof UtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/connexion': typeof ConnexionRoute
  '/eclairage': typeof EclairageRoute
  '/energie': typeof EnergieRoute
  '/securite': typeof SecuriteRoute
  '/senior': typeof SeniorRoute
  '/utilisateurs': typeof UtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acces'
    | '/connexion'
    | '/eclairage'
    | '/energie'
    | '/securite'
    | '/senior'
    | '/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acces'
    | '/connexion'
    | '/eclairage'
    | '/energie'
    | '/securite'
    | '/senior'
    | '/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/acces'
    | '/connexion'
    | '/eclairage'
    | '/energie'
    | '/securite'
    | '/senior'
    | '/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesRoute: typeof AccesRoute
  ConnexionRoute: typeof ConnexionRoute
  EclairageRoute: typeof EclairageRoute
  EnergieRoute: typeof EnergieRoute
  SecuriteRoute: typeof SecuriteRoute
  SeniorRoute: typeof SeniorRoute
  UtilisateursRoute: typeof UtilisateursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senior': {
      id: '/senior'
      path: '/senior'
      fullPath: '/senior'
      preLoaderRoute: typeof SeniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energie': {
      id: '/energie'
      path: '/energie'
      fullPath: '/energie'
      preLoaderRoute: typeof EnergieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eclairage': {
      id: '/eclairage'
      path: '/eclairage'
      fullPath: '/eclairage'
      preLoaderRoute: typeof EclairageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acces': {
      id: '/acces'
      path: '/acces'
      fullPath: '/acces'
      preLoaderRoute: typeof AccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesRoute: AccesRoute,
  ConnexionRoute: ConnexionRoute,
  EclairageRoute: EclairageRoute,
  EnergieRoute: EnergieRoute,
  SecuriteRoute: SecuriteRoute,
  SeniorRoute: SeniorRoute,
  UtilisateursRoute: UtilisateursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
